
export { Dashboard } from './dashboard'
export { Login } from './login'
export { Signup } from './signup'
export { LatestReleases} from './LatestReleases'
export { Populars } from './Populars'
export { Logout } from './Logout'
export { BetterMovies } from './BetterMovies'
export { Search } from './Search'
export { DescriptPage } from './DescriptPage'